test_migration

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -184,44 +184,43 @@ jobs:
           name: Configure server
           command: |
             # Your code here
-            ls 
             ansible-playbook -i /tmp/ansible/inventory.txt .circleci/ansible/configure-server.yml
 
       # Here's where you will add some code to rollback on failure      
 
-#   run-migrations:
-#     docker:
-#       # Docker image here that supports NodeJS
-#       - image: circleci/node:13.8.0 
-#     steps:
-#       # Checkout code from git
-#       - checkout
-#       - run:
-#           name: Run migrations
-#           command: |
-#             # Your code here
-#             cd backend
-#             npm i 
-#             npm run migrations >> migrations.txt
-#       - run:
-#           name: check migration result
-#           command: |
-#             echo "migration_result"
-#             cat migrations.txt
-#       - run:
-#           name: Send migration results to memstash
-#           command: |
-#             # Your code here
-#             if grep -q "has been executed successfully" migrations.txt; 
-#             then
-#               echo "Migration Success"
-#               Migration=1
-#               curl -H "Content-Type: text/plain" -H "token: 3e8bea18-bb6f-4894-8b6a-676b3d860883" \
-#               --request PUT --data "$Migration" https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID}
-#             else
-#               echo "Migration Failed"
-#               exit 1
-#             fi
+  run-migrations:
+    docker:
+      # Docker image here that supports NodeJS
+      - image: circleci/node:13.8.0 
+    steps:
+      # Checkout code from git
+      - checkout
+      - run:
+          name: Run migrations
+          command: |
+            # Your code here
+            cd backend
+            npm i 
+            npm run migrations >> migrations.txt
+      - run:
+          name: check migration result
+          command: |
+            echo "migration_result"
+            cat migrations.txt
+      - run:
+          name: Send migration results to memstash
+          command: |
+            # Your code here
+            if grep -q "has been executed successfully" migrations.txt; 
+            then
+              echo "Migration Success"
+              Migration=1
+              curl -H "Content-Type: text/plain" -H "token: 3e8bea18-bb6f-4894-8b6a-676b3d860883" \
+              --request PUT --data "$Migration" https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID}
+            else
+              echo "Migration Failed"
+              exit 1
+            fi
 
 
 
@@ -343,8 +342,8 @@ workflows:
               only: [test-feature-branch]
       - configure-infrastructure:
           requires: [deploy-infrastructure]
-      # - run-migrations:
-      #     requires: [configure-infrastructure]
+      - run-migrations:
+          requires: [configure-infrastructure]
       # - deploy-frontend:
       #     requires: [run-migrations]
       # - deploy-backend:
