run_migration_implemented

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -43,7 +43,8 @@ jobs:
       - run:
           name: Build front-end
           command: |
-            run: npm run build
+            cd frontend
+            npm run build
       - save_cache:
           paths: [frontend/node_modules]
           key: frontend-build
@@ -58,89 +59,140 @@ jobs:
       - run:
           name: Back-end build
           command: |
-            run: npm run build
+            cd frontend
+            npm run build
       - save_cache:
           paths: [backend/node_modules]
           key: backend-build
 
   test-frontend:
     docker:
-      # Docker image here
+      - image: circleci/node:13.8.0
     steps:
       # Checkout code from git
+      - checkout
       # Restore from cache
+      - restore_cache:
+        keys: [frontend-build] 
       # Your job code here
+      - run: 
+        name: Unit Test Frontend
+        command: |
+          cd frontend
+          npm run test 
+
                 
   test-backend:
     docker:
       # Docker image here
+      - image: circleci/node:13.8.0
     steps:
       # Checkout code from git
+      - checkout
       # Restore from cache
+      - restore_cache:
+        keys: [backend-build]
       # Your job code here
+      - run:
+        name: Unit Test Backend
+        command: |
+          cd backend
+          npm run test
+
             
   scan-frontend:
     docker:
       # Docker image here
+      - image: circleci/node:13.8.0
     steps:
       # Checkout code from git
+      - checkout 
       # Restore from cache
+      - restore_cache:
+        keys: [frontend-build]
       # Your job code here
+      - run:
+        name: Scan Frontend
+        command: |
+          cd frontend
+          npm run audit --audit-level=critical
 
   scan-backend:
     docker:
       # Docker image here
+      - image: circleci/node:13.8.0 
     steps:
       # Checkout code from git
+      - checkout 
       # Restore from cache
+      - restore_cache:
+        keys: [backend-build]
       # Your job code here
+      - run:
+        name: Scan Backend
+        command: |
+          cd backend
+          npm run audit --audit-level=critical      
 
   deploy-infrastructure:
     docker:
       # Docker image here that supports AWS CLI
+      - image: circleci/node:13.8.0 
     steps:
       # Checkout code from git
+      - checkout
       - run:
           name: Ensure back-end infrastructure exists
           command: |
             aws cloudformation deploy \
               --template-file .circleci/files/backend.yml \
-              #--tags project=your-tag \
-              # --stack-name "your back-end stack name with workflow id" \
-              # --parameter-overrides ID="your workflow id"  
-              exit 1
+              --tags Key=Name,Value=backend \
+              --stack-name "${CIRCLE_WORKFLOW_ID0:7}-backend" \
+              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID0:7}"
+            URL=$(aws ec2 describe-instances --region us-west-2 --query "Reservations[*].Instances[*].PublicIpAddress" \
+                  --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" --output text) 
+            curl -H "Content-Type: text/plain" -H "token: 3e8bea18-bb6f-4894-8b6a-676b3d860883" --request PUT \
+                 --data "$URL" https://api.memstash.io/values/url_${CIRCLE_WORKFLOW_ID:0:7}
       - run:
           name: Ensure front-end infrastructure exist
           command: |
             aws cloudformation deploy \
               --template-file .circleci/files/frontend.yml \
-              #--tags project=your-tag \
-              # --stack-name "your front-end stack name with workflow id" \
-              # --parameter-overrides ID="your workflow id"  
-              exit 1
+              --tags Key=Name, Value=frontend \
+              --stack-name "${CIRCLE_WORKFLOW_ID0:7}-frontend"\
+              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID0:7}" 
       - run:
           name: Add back-end ip to ansible inventory
           command: |
             # Your code here
-            exit 1
+            aws ec2 describe-instances --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}"  \
+              --query 'Reservations[*].Instances[*].PublicIpAddress' \
+              --output text >> .circleci/ansible/inventory.txt
       - persist_to_workspace:
           root: ~/
           paths:
             - project/.circleci/ansible/inventory.txt
-      # Here's where you will add some code to rollback on failure      
+      # Here's where you will add some code to rollback on failure
+      #- destroy-environments      
 
   configure-infrastructure:
     docker:
       # Docker image here that supports Ansible
+      - image: python:3.7-alpine3.11
     steps:
       # Checkout code from git
+      - checkout
       # Add ssh keys with fingerprint
+      - add_ssh_keys:
+          fingerprints: ["69:ef:2c:d0:14:7b:78:eb:53:7d:b7:d9:95:7f:ec:e2"]
       # attach workspace
+      - attach_workspace:
+          at: /tmp/ansible
       - run:
           name: Install dependencies
           command: |
             # Your code here
-            exit 1
+            apk add --
       - run:
           name: Configure server
           command: |
@@ -151,18 +203,39 @@ jobs:
   run-migrations:
     docker:
       # Docker image here that supports NodeJS
+      - image: circleci/node:13.8.0 
     steps:
       # Checkout code from git
+      - checkout
       - run:
           name: Run migrations
           command: |
             # Your code here
-            exit 1
+            cd backend
+            npm i 
+            npm run migrations >> migrations.txt
+      - run:
+          name: check migration result
+          command: |
+            echo "migration_result"
+            cat migrations.txt
       - run:
           name: Send migration results to memstash
           command: |
             # Your code here
-            exit 1
+            if grep -q "has been executed successfully" migrations.txt; 
+            then
+              echo "Migration Success"
+              Migration=1
+              curl -H "Content-Type: text/plain" -H "token: 3e8bea18-bb6f-4894-8b6a-676b3d860883" \
+              --request PUT --data "$Migration" https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID}
+            else
+              echo "Migration Failed"
+              exit 1
+            fi
+
+
+
      # Here's where you will add some code to rollback on failure      
 
   deploy-frontend:
